- hosts: webserver
  vars_files:
  - credentials.yml
  tasks: 
  - name: package httpd 
    package:
      name: "httpd"
      state: present
    when: ansible_distribution == "RedHat"
    register: x

  - name: doc root directory
    file:
      state: directory
      dest: "/var/www/neeraj"
    register: y
    tags: webgit

  - name: copy web page from local system
    copy:
      src: "index.html"
      dest: "/var/www/neeraj"
    when: y.failed == false
    tags: webpage

  - name: service start
    service:
      name: httpd
      state: started

  handlers:
  - name: service httpd
    service:
      name: httpd
      state: restarted

  - name: service httpd
    service:
      name: httpd
      state: restarted
  - name: conf webserver 
    template:
      dest: /etc/httpd/conf.d/neeraj.conf
      src: files/localconf.conf
    when: x.rc == 0
    tags: webconf
    notify: service httpd
    

      

